# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
repos:
- repo: local
  hooks:
  ## Rust hooks
  - id: fmt
    name: fmt
    language: system
    entry: just fmt
    types_or: [rust, cargo, cargo-lock]
    stages: [pre-commit, pre-merge-commit, manual]
    pass_filenames: false
  - id: fmt-check
    name: fmt-check
    language: system
    entry: just fmt-check
    types_or: [rust, cargo, cargo-lock]
    stages: [pre-push, manual]
    pass_filenames: false
  - id: check
    name: check
    language: system
    entry: just check
    types_or: [rust, cargo, cargo-lock]
    stages: [pre-push, manual]
    pass_filenames: false
  - id: check-unused-deps
    name: check-unused-deps
    language: system
    entry: just check-unused-deps
    types_or: [rust, cargo, cargo-lock]
    stages: [pre-push, manual]
    pass_filenames: false
